name: whatsapp
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.7.2
  flutter_chat_ui: ^2.6.2
  flutter_chat_types: ^3.6.2
  zego_uikit_prebuilt_call: ^4.17.6
  flutter_launcher_icons: ^0.14.4
  shared_preferences: ^2.5.3
  firebase_core: ^3.15.1
  firebase_auth: ^5.6.2
  cloud_firestore: ^5.6.11
  firebase_messaging: ^15.2.9
  intl_phone_number_input: ^0.7.4

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "icons/icon.png"
  min_sdk_android: 21

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - icons/icon.png
    - icons/icon_use.jpeg
    - icons/icons.jpeg
